module.exports = {
    AIRTABLE_API_KEY: process.env.AIRTABLE_API_KEY,
    JWT_SECRET_KEY: process.env.JWT_SECRET_KEY,
    MAILER_DELIVERY_METHOD: process.env.MAILER_DELIVERY_METHOD,
    MAILER_HOST: process.env.MAILER_HOST,
    MAILER_USERNAME: process.env.MAILER_USERNAME,
    MAILER_PASSWORD: process.env.MAILER_PASSWORD,
}