export default {
    "Empty": "transparent",
    "Black": '#000000',
    "Blue Purple": '#9CC7FF',
    "Brass": '#B87503',
    "Brown": '#B87504',
    "Brushed Nickel": '#EEEEEC',
    "Cherry": '#BA1E45',
    "Corduroy": '#FFA981',
    "Cotton": '#FFDAF6',
    "Cream": '#FFEAB6',
    "Dark Wood": '#666666',
    "Dove": '#EEEEEA',
    "Fern": '#93E088',
    "Foam Beans": '#FEE2D5',
    "Framboise": '#FFDCE5',
    "Glass": '#D1F7C4',
    "Glazed Ceramic": '#C2F5E9',
    "Glazed Ceramic Base, Linen Shade": '#D0F0FD',
    "Gold": '#FCB400',
    "Green": '#20C933',
    "Grey": '#CCCCCC',
    "Indian Wool": '#CDB0FF',
    "Iron": '#777777',
    "Lacquered Ash": '#FF9EB7',
    "Leather": '#FFA982',
    "Leather Cowhide": '#FFA985',
    "Light Wood": '#FFEAB8',
    "Marble": '#EEEEED',
    "Matte Black": '#444444',
    "Metal": '#CCCCC5',
    "Mirror": '#D0F0FA',
    "Orange": '#FFA500',
    "Poly-cotton Shade": '#338A17',
    "Reclaimed Wood": '#D74D26',
    "Red": '#FF0000',
    "Rough": '#FFDCE3',
    "Shiny Black": '#888888',
    "Silver": '#CCCCC8',
    "Solid Maple": '#B87502',
    "Solid Teak": '#B87501',
    "Stainless Steel": '#CCCCCA',
    "Steel": '#CCCCCF',
    "Suede": '#FEE2D7',
    "Taupe": '#FFEAB4',
    "Tech Suede": '#FEE2D9',
    "Velvet": '#8B46FF',
    "Viscose": '#CDB0FA',
    "Walnut": "#FFD66F",
    "White": '#EEEEEF',
    "White Ash": '#EEEEEE',
    "Wool": '#FFD66E',
    "Yellow": '#FFFF00',
}